before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: sbomreport-to-dependencytrack-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/takumakume/sbomreport-to-dependencytrack/version.Version={{.Version}}
-
  id: sbomreport-to-dependencytrack-darwin-windows
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/takumakume/sbomreport-to-dependencytrack/version.Version={{.Version}}
-
  id: sbomreport-to-dependencytrack-darwin-arm64
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - arm64
  ldflags:
    - -s -w -X github.com/takumakume/sbomreport-to-dependencytrack/version.Version={{.Version}}    
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-dev"
changelog:
  skip: true
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - 'docker.io/takumakume/sbomreport-to-dependencytrack:{{ .Version }}-amd64'
      - 'docker.io/takumakume/sbomreport-to-dependencytrack:latest-amd64'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/takumakume/sbomreport-to-dependencytrack"
      - "--platform=linux/amd64"
  -
    goos: linux
    goarch: arm64
    image_templates:
      - 'docker.io/takumakume/sbomreport-to-dependencytrack:{{ .Version }}-arm64'
      - 'docker.io/takumakume/sbomreport-to-dependencytrack:latest-arm64'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/takumakume/sbomreport-to-dependencytrack"
      - "--platform=linux/arm64"

docker_manifests:
- name_template: 'takumakume/sbomreport-to-dependencytrack:{{ .Version }}'
  image_templates:
  - 'takumakume/sbomreport-to-dependencytrack:{{ .Version }}-arm64'
  - 'takumakume/sbomreport-to-dependencytrack:{{ .Version }}-amd64'
- name_template: 'takumakume/sbomreport-to-dependencytrack:latest'
  image_templates:
  - 'takumakume/sbomreport-to-dependencytrack:latest-arm64'
  - 'takumakume/sbomreport-to-dependencytrack:latest-amd64'
