apiVersion: v1
entries:
  sbomreport-to-dependencytrack:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-08-25T22:22:47.217616+09:00"
    description: A server that receives webhooks from trivy-operator and sends SBOMReport
      to Dependency Track
    digest: d780e90cca472b32042d230b94f73f4607fed70cf3f58357a13842fcea94285b
    name: sbomreport-to-dependencytrack
    type: application
    urls:
    - sbomreport-to-dependencytrack-0.0.1.tgz
    version: 0.0.1
generated: "2023-08-25T22:22:47.215786+09:00"
