apiVersion: v1
entries:
  sbomreport-to-dependencytrack:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-08-25T17:42:50.220418+09:00"
    description: A server that receives webhooks from trivy-operator and sends SBOMReport
      to Dependency Track
    digest: a30ab5a397dfa3788c4931a619de582c7beddadf0eb09d169947b90e3dcd6d9f
    name: sbomreport-to-dependencytrack
    type: application
    urls:
    - sbomreport-to-dependencytrack-0.0.1.tgz
    version: 0.0.1
generated: "2023-08-25T17:42:50.219395+09:00"
