apiVersion: v1
entries:
  sbomreport-to-dependencytrack:
  - apiVersion: v2
    appVersion: 0.0.7
    created: "2023-11-22T23:53:38.935377+09:00"
    description: A server that receives webhooks from trivy-operator and sends SBOMReport
      to Dependency Track
    digest: 253ea0b58c97f7b907ec913090b67970b2f39e79ef8420b6ebdc5a04c6f71dd6
    name: sbomreport-to-dependencytrack
    type: application
    urls:
    - sbomreport-to-dependencytrack-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2023-11-22T23:53:38.934635+09:00"
    description: A server that receives webhooks from trivy-operator and sends SBOMReport
      to Dependency Track
    digest: ee4f60a379d8ef9ce405977345dbe14bd598e94cca3d72bc8ab1b36688068d9e
    name: sbomreport-to-dependencytrack
    type: application
    urls:
    - sbomreport-to-dependencytrack-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-11-22T23:53:38.934067+09:00"
    description: A server that receives webhooks from trivy-operator and sends SBOMReport
      to Dependency Track
    digest: 693b7e029f1e30e36ce65ae7a02ac0a70839f7450b23d26ed13cbae53d7d2ab0
    name: sbomreport-to-dependencytrack
    type: application
    urls:
    - sbomreport-to-dependencytrack-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2023-11-22T23:53:38.930681+09:00"
    description: A server that receives webhooks from trivy-operator and sends SBOMReport
      to Dependency Track
    digest: cca505057081030feee4812509ad0986001f7c37c3514caafd4c8ab70baadfb6
    name: sbomreport-to-dependencytrack
    type: application
    urls:
    - sbomreport-to-dependencytrack-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2023-11-22T23:53:38.929957+09:00"
    description: A server that receives webhooks from trivy-operator and sends SBOMReport
      to Dependency Track
    digest: 9d9bc5fab1e9b574d4adb66335525b49c048ffc91292ea30351e1535aabdec69
    name: sbomreport-to-dependencytrack
    type: application
    urls:
    - sbomreport-to-dependencytrack-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2023-11-22T23:53:38.929185+09:00"
    description: A server that receives webhooks from trivy-operator and sends SBOMReport
      to Dependency Track
    digest: 43229b5436c7720a491b04e709c3fd4cb094011b6b6d3f55696dbb3d693af7ea
    name: sbomreport-to-dependencytrack
    type: application
    urls:
    - sbomreport-to-dependencytrack-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-11-22T23:53:38.928375+09:00"
    description: A server that receives webhooks from trivy-operator and sends SBOMReport
      to Dependency Track
    digest: d780e90cca472b32042d230b94f73f4607fed70cf3f58357a13842fcea94285b
    name: sbomreport-to-dependencytrack
    type: application
    urls:
    - sbomreport-to-dependencytrack-0.0.1.tgz
    version: 0.0.1
generated: "2023-11-22T23:53:38.927493+09:00"
